CFLAGS = --std=c++17 -Wall -Werror --pedantic

all:
	clang $(CFLAGS) -o shadows_of_the_knight_ep_1.bin shadows_of_the_knight_ep_2.cpp

windows:
	clang $(CFLAGS) -o shadows_of_the_knight_ep_1.exe shadows_of_the_knight_ep_2.cpp
